### PR TITLE
Feature: Default State Creator

### PR DESCRIPTION
**Pull request by DragonRaider5**
Hi,

I'm in a situation where I need to check the local storage in order to initially populate my state (as it holds device preferences which got auto-detected and/or set by the user before).
Works great!

But now I also need to reset my redux state while the application is running (when the user logs out) - which also works nicely, no problems.
However if you put those two features together, you have a problem... The state will always be rehydrated based on the (old, maybe outdated) local storage data from the first page load.

This is why I decided to allow for default state creator functions in handleAction(s)!

I think that I'm not the only one having such a use case (where the default state must be "up to date" at every reset) - that's why I decided to share this PR.
In addition this feature allows for async data fetching in your `getDefaultState()` by being able to make async calls in it, return your bare bone default state and dispatch an action when the async operation finishes.

Example:
```js
import { handleActions } from 'redux-actions'

import store from './store.js'
import { fetchSomeData } from './service.js'
import { fetchSomeData as fetchSomeDataAction } from './actions.js'

const getDefaultState = () => {
  // perform some time of execution critical and/or async task here
  fetchSomeData()
    .then((data) => store.dispatch(fetchSomeDataAction(data))

  const preferences = JSON.parse(window.localStorage.getItem('preferences'))

  return {
    preferences,
    someData: null
  }
}

export default handleActions({
  [fetchSomeDataAction]: (state, action) => ({
    ...state,
    someData: action.payload
  })
}, getDefaultState)
`
``

### CODE REVIEW

**Comment by timche** [comment]
Something like this should be handled in a dedicated action when starting the app in `componentDidMount`.

**Comment by DragonRaider5** [comment]
As I already mentioned, this PR isn't about app startup - for this case you could simply execute the function getDefaultState().

It's about when the state has gotten reset while the app is running - for example after a logout.

**Comment by timche** [comment]
We are aligning with the concept of Redux:

> We'll start by specifying the initial state. Redux will call our reducer with an `undefined` state for the first time.

https://redux.js.org/basics/reducers#handling-actions

Which means the initial state is only being used at start up and should stay like this.

**Comment by DragonRaider5** [comment]
Yeah, but what about user-triggered restarts?

A logout means a completely new startup of the app (with clean data) which is user-triggered, which should thereby result in an `undefined` state.

**Comment by timche** [comment]
That's correct, but still `handleActions` shouldn't do any side-effects.

> It's very important that the reducer stays pure. Things you should never do inside a reducer:
>
> - Mutate its arguments;
> - Perform side effects like API calls and routing transitions;
> - Call non-pure functions, e.g. Date.now() or Math.random().

https://redux.js.org/basics/reducers#handling-actions

Please move any side-effects to the action creator and use something like redux-thunk.

**Pull request closed without merging**
