### PR TITLE
FSA Sequence

### PR DESCRIPTION
**Pull request by tappleby**
This is PR #19 without the extra arguments changes.

I was going to add documentation for handling sequence's but we don't have anything in the FSA spec that mentions this yet (requires resolution for acdlite/flux-standard-action#7).

### CODE REVIEW

**Comment by timche** [comment]
Can rebase please? Would like to see if the tests are still running with the latest master. Otherwise this change looks fine to me. I'll reach out to @acdlite for that later.

**Comment by Lexicality** [comment]
I've got a rebased version working at [smarkets/redux-actions](https://github.com/smarkets/redux-actions), looks like the tests do pass.

**Comment by timche** [comment]
Thanks for doing it. Is this PR still a thing?

**Comment by Lucretiel** [comment]
If this gets merged, I'll update my own [PR](https://github.com/acdlite/redux-actions/pull/97) as well with the rename.

**Comment by timche** [comment]
PR is dead.

**Pull request closed without merging**
